// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327025625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ProjectContexts.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("LifeTime", "Domain.ProjectContexts.Project.LifeTime#ProjectLifeTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("CreatedAt")
                                .HasColumnType("date")
                                .HasColumnName("created_at");

                            b1.Property<DateOnly?>("FinishedAt")
                                .HasColumnType("date")
                                .HasColumnName("finished_at");
                        });

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Domain.ProjectContexts.Project", b =>
                {
                    b.OwnsMany("Domain.ProjectContexts.Entities.ProjectTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("task_description");

                            b1.Property<int>("Limit")
                                .HasColumnType("integer")
                                .HasColumnName("members_limit");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("project_tasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.OwnsMany("Domain.ProjectContexts.Entities.ProjectTaskMemberInfo", "TaskMembers", b2 =>
                                {
                                    b2.Property<Guid>("MemberId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("member_id");

                                    b2.Property<string>("MemberEmail")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("member_email");

                                    b2.Property<string>("MemberLogin")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("member_login");

                                    b2.Property<Guid>("ProjectTaskId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("MemberId");

                                    b2.HasIndex("ProjectTaskId");

                                    b2.ToTable("project_task_members", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectTaskId");
                                });

                            b1.OwnsOne("Domain.ProjectContexts.Entities.ProjectTaskStatusInfo", "StatusInfo", b2 =>
                                {
                                    b2.Property<Guid>("ProjectTaskId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("ProjectTaskId");

                                    b2.ToTable("project_tasks");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectTaskId");

                                    b2.OwnsOne("Domain.ProjectContexts.Entities.ProjectTaskSchedule", "Schedule", b3 =>
                                        {
                                            b3.Property<Guid>("ProjectTaskStatusInfoProjectTaskId")
                                                .HasColumnType("uuid");

                                            b3.Property<DateTime?>("Closed")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("task_closed_at");

                                            b3.Property<DateTime>("Created")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("task_created_at");

                                            b3.HasKey("ProjectTaskStatusInfoProjectTaskId");

                                            b3.ToTable("project_tasks");

                                            b3.WithOwner()
                                                .HasForeignKey("ProjectTaskStatusInfoProjectTaskId");
                                        });

                                    b2.OwnsOne("Domain.ProjectContexts.Entities.ProjectTaskStatus", "Status", b3 =>
                                        {
                                            b3.Property<Guid>("ProjectTaskStatusInfoProjectTaskId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("status_name");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("status_value");

                                            b3.HasKey("ProjectTaskStatusInfoProjectTaskId");

                                            b3.ToTable("project_tasks");

                                            b3.WithOwner()
                                                .HasForeignKey("ProjectTaskStatusInfoProjectTaskId");
                                        });

                                    b2.Navigation("Schedule")
                                        .IsRequired();

                                    b2.Navigation("Status")
                                        .IsRequired();
                                });

                            b1.Navigation("StatusInfo")
                                .IsRequired();

                            b1.Navigation("TaskMembers");
                        });

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
